### ISSUE TITLE
Not identifying pangrams in Chrome 90

### ISSUE THREAD

**Issue by crdennett** [draber/draber.github.io#62]
Just upgraded my Fedora Linux system to Chrome 90.  Neither the bookmarklet nor the extension are underlining the pangram in todays (4/16/21) spelling bee.  The bookmarklet was working in Chrome 89.  Can't say for the extension as I just installed in for the first time on Chrome 90.  Not a big deal but I thought you should know.

**Comment by draber** [comment]
Good catch! I just tried it on Win10/64 Chrome 90 and it's missing the underline as well. - Thanks for bringing this up!

**Comment by draber** [comment]
Turns out, this has nothing to do with Chrome at all, but with the recent design changes. Should be fixed soon.

**Comment by draber** [comment]
The issue has been fixed in v3.0.1. The new extension has been submitted to the app stores. It usually takes a few days before they are tested and published.
