### ISSUE TITLE
Maybe link the new Bee forum somewhere?

### ISSUE THREAD

**Issue by gitonthescene** [draber/draber.github.io#88]
Hey, this looks super cool.  Now that there’s a dedicated [Spelling Bee forum](https://www.nytimes.com/2021/07/27/crosswords/spelling-bee-2021-07-27.html) it might be nice to have a link to it from the assistant since the forum has people discussing the day’s puzzle and even offering creative hints.  Finding the column for the day should be trivial.  Just a thought..

**Comment by draber** [comment]
Not a bad idea, I will think about it

**Comment by gitonthescene** [comment]
Also, some people try to reach Genius without entering any four-letter words.  It might be neat to have another button besides Enter where you could add to a "notepad" instead which could be viewed after reaching Genius.  I know that some users do this now by taking notes of four-letter words they haven't yet entered.

**Comment by draber** [comment]
@gitonthescene 

I wonder where to place the link for the forum. In fact, I would need to create multiple links, for instance also to https://www.reddit.com/r/NYTSpellingBee/.  Somebody had suggested placing it next to _Yesterday's answers_, but there is no space on smaller screens. I'm undecided yet.

I won't implement the notepad, and there are multiple reasons:

- I would need to temper with Spelling Bee in a way that could hurt NYT's copyrights, something I absolutely don't want. I depend on their goodwill
- It would need a lot of space. The latest release on the other hand was all about gaining space to make the Assistant more suitable for mobiles
- I don't use the feature myself

**Comment by gitonthescene** [comment]
No worries.  Thanks for getting back.  I just thought I'd offer it as a suggestion.  Should I close this issue? Or would you rather leave it open to think about the link to the forum?

**Comment by draber** [comment]
I will close it, but I added the link idea to my idealist. And thanks a lot for your input!
